[package]
name = "temple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
temple-macros = { path = "../temple-macros" }
temple-common = { path = "../temple-common" }
